### ISSUE TITLE
Is it possible to insert an `Image` Cell ?

### ISSUE THREAD

**Issue by Smurf-IV** [rabanti-github/PicoXLSX#15]

**Comment by rabanti-github** [comment]
Hello
The short answer is: No, it is not supported

The long answer:
Actually, there is no such thing like a Image cell (as fas as I know). You probably mean an embedded image in a worksheet.
Currently, no other content than cell data (Strings, Numbers, Dates and Times, Booleans, empty and formulas) are supported. Other limitations are in-line formatting of cells, reading of styles, workbook encryption or pivot tables.
Embedded objects like diagrams, images or file attachments are currently not on the roadmap.
If you need such content, you may consider NPOI, instead of NanoXLSX.

**Comment by rabanti-github** [comment]
I will close this issue for now.
Please do not hesitate to ask further questions, to file bugs, or to make proposals.
Thank you.
