### ISSUE TITLE
Webapi how return workbook

### ISSUE THREAD

**Issue by visualczm** [rabanti-github/PicoXLSX#17]
Hi,
I'm come in , again~
See title，thank you for your help~

**Comment by rabanti-github** [comment]
Hi,
Can you quickly describe a little bit more, what you want to do?
Do you try to create workbooks on a web server (e.g. ASP.NET) and then to provide them by browser download?
Thank you in advance for the information.

**Comment by visualczm** [comment]
hi，
`Do you try to create workbooks on a web server (e.g. ASP.NET) and then to provide them by browser download?`
Yeah，but is .net5 webapi in web server ,i want return picoxlsx create file.
how did you do that?

**Comment by rabanti-github** [comment]
Unfortunately, until now, I have not really worked with web servers in .net (had more to deal with Node and recently Java).
However, from my Java experience, I could imagine that it should work like that:
- Create the workbook as usual
- Create a MemoryStream and use the SaveAsStream function (in Workbook) to store the WB
- Reset the MemoryStream
- Pass the stream to the function of the web server that provides binary downloads
- You probably have to define a MIME type for the download process (**application/vnd.openxmlformats-officedocument.spreadsheetml.sheet**), otherwise the browser does not know how to handle the download. Since the stream contains already the final XLSX file, no further container operations have to be done (probably)

Maybe I can do some research for this topic in the evening. I hope this helps in the meantime.

**Comment by rabanti-github** [comment]
Maybe this could be the solution (if it is the right .net version):
https://codeburst.io/download-files-using-web-api-ae1d1025f0a9
In this case, you could convert the MemoryStream into a byte array (https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream.toarray?view=net-5.0) and define the MIME type, as earlier described:

```cs
MemoryStream ms = new MemoryStream();
workbook.SaveAsStream(ms, true);
ms.Seek(0, SeekOrigin.Begin); // not sure whether this is necessary
byte[] bytes = ms.ToArray();
return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "workbook.xlsx");
```

Disclaimer: This is not tested code (just written down here in this comment)

I hope, this helps

**Comment by visualczm** [comment]
Thank you so much~
Is worked
