### ISSUE TITLE
Setting a custom column width doesn't work

### ISSUE THREAD

**Issue by JohanLindvall** [rabanti-github/PicoXLSX#5]
Fixed in https://github.com/rabanti-github/PicoXLSX/pull/4

This can be verified by running demo4.

**Comment by rabanti-github** [comment]
Fixed with commit 9f8b30716324875b902a74040d0570f3d72bd11b <strike>and new version released with commit 5b6f76e523155d9230e52acd1dd17cde1ea2bf30</strike>.

The nuget package as well as the <strike>fix</strike> several patches for the Java versions will be published this evening.

Thank you for your contribution.
