### ISSUE TITLE
Setting the value type in the Cell constructors doesn't work

### ISSUE THREAD

**Issue by JohanLindvall** [rabanti-github/PicoXLSX#7]
The value type is always "guessed" in the base Cell constructor, overriding what the user chooses.

Fixed in https://github.com/rabanti-github/PicoXLSX/pull/6.

**Comment by rabanti-github** [comment]
I withdrew release 2.3.2 and will merge this changes with the previous fix.

* Type decimal: Additionally to decimal, I will check other types like uint, byte and consider to add them as well.
* Constructor argument DEFAULT: I have to check some functions (e.g. addRange()) that could access the constructor and also rely on DEFAULT. If I remember correctly, was the auto-guessing function not implemented in early versions (thus the type definition was mandatory) and this misbehavior may be originating form a code cleanup. But your proposed fix should be not a problem. 

I deal with that this evening.
Please let me know, if you find further issues or missing features.

Thank you in advance.

**Comment by JohanLindvall** [comment]
Thanks, we will be testing and using your library in the coming days.

**Comment by rabanti-github** [comment]
Supported are now:
* byte
* sbyte
* decimal
* float
* int
* uint
* long
* ulong
* short
* ushort

The constructors of Cell do now only perform a auto-casting if Type set to DEFAULT (since this is an internal type and not existing in Excel). Therefore, if you define:

```c#
decimal dcVal = 1.223m;
Cell c = new Cell(dcVal, Cell.CellType.NUMBER);
```
... the type is kept at CellType.NUMBER.
However, it is recommend to use AddCell() or AddNextCell(), since no type must be specified there.
Is this the behavior you looked for? I assume you had problems that the decimal type was casted to a string. If you intend to store other types than the primitive data types, strings or DateTime objects into cells, I have too look into the LowLevel methods, since Excel is quite picky when it comes to wrong casted data. 

Ist this state OK for you?

**Comment by JohanLindvall** [comment]
Thanks, this looks OK.
